[ N 2022-12-15 14:08:31.5181 18810/T1 age/Wat/WatchdogMain.cpp:1377 ]: Starting Passenger watchdog...
[ N 2022-12-15 14:08:31.5468 18812/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2022-12-15 14:08:31.5470 18812/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2022-12-15 14:08:31.5704 18812/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 18812
[ N 2022-12-15 14:08:34.5713 18812/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
App 18841 output: Error: The application encountered the following error: cannot load such file -- sinatra/base (LoadError)
App 18841 output:     /Users/seamusconnolly/Desktop/telegram-binance-bot/index.rb:2:in `require'
App 18841 output:     /Users/seamusconnolly/Desktop/telegram-binance-bot/index.rb:2:in `<top (required)>'
App 18841 output:     config.ru:1:in `require'
App 18841 output:     config.ru:1:in `block in <main>'
App 18841 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-3.0.2/lib/rack/builder.rb:118:in `instance_eval'
App 18841 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-3.0.2/lib/rack/builder.rb:118:in `initialize'
App 18841 output:     config.ru:1:in `new'
App 18841 output:     config.ru:1:in `<main>'
App 18841 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 18841 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 18841 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 18841 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
App 18841 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 18841 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 18841 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2022-12-15 14:08:35.2612 18812/Tr age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /Users/seamusconnolly/Desktop/telegram-binance-bot: The application encountered the following error: cannot load such file -- sinatra/base (LoadError)
  Error ID: 4142ebd9
  Error details saved to: /var/folders/p_/06q3c1qn0dsbgl8rc6g82gy00000gn/T//passenger-error-jpI0qd.html

[ E 2022-12-15 14:08:35.2682 18812/T9 age/Cor/Con/CheckoutSession.cpp:283 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 4142ebd9. Please see earlier logs for details about the error.

[ N 2022-12-15 14:08:49.7188 18812/T9 age/Cor/CoreMain.cpp:671 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ N 2022-12-15 14:08:49.7189 18812/T1 age/Cor/CoreMain.cpp:1246 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ N 2022-12-15 14:08:49.7189 18812/Ta Ser/Server.h:901 ]: [ServerThr.2] Freed 0 spare client objects
[ N 2022-12-15 14:08:49.7190 18812/Ta Ser/Server.h:558 ]: [ServerThr.2] Shutdown finished
[ N 2022-12-15 14:08:49.7190 18812/Te Ser/Server.h:901 ]: [ServerThr.4] Freed 0 spare client objects
[ N 2022-12-15 14:08:49.7190 18812/Te Ser/Server.h:558 ]: [ServerThr.4] Shutdown finished
[ N 2022-12-15 14:08:49.7190 18812/Th Ser/Server.h:901 ]: [ServerThr.5] Freed 0 spare client objects
[ N 2022-12-15 14:08:49.7191 18812/Th Ser/Server.h:558 ]: [ServerThr.5] Shutdown finished
[ N 2022-12-15 14:08:49.7191 18812/Ti Ser/Server.h:901 ]: [ServerThr.6] Freed 0 spare client objects
[ N 2022-12-15 14:08:49.7192 18812/Ti Ser/Server.h:558 ]: [ServerThr.6] Shutdown finished
[ N 2022-12-15 14:08:49.7191 18812/Tk Ser/Server.h:901 ]: [ServerThr.7] Freed 0 spare client objects
[ N 2022-12-15 14:08:49.7192 18812/Tk Ser/Server.h:558 ]: [ServerThr.7] Shutdown finished
[ N 2022-12-15 14:08:49.7191 18812/Tm Ser/Server.h:901 ]: [ServerThr.8] Freed 0 spare client objects
[ N 2022-12-15 14:08:49.7193 18812/Tm Ser/Server.h:558 ]: [ServerThr.8] Shutdown finished
[ N 2022-12-15 14:08:49.7190 18812/Tc Ser/Server.h:901 ]: [ServerThr.3] Freed 0 spare client objects
[ N 2022-12-15 14:08:49.7193 18812/Tc Ser/Server.h:558 ]: [ServerThr.3] Shutdown finished
[ N 2022-12-15 14:08:49.7189 18812/T9 Ser/Server.h:901 ]: [ServerThr.1] Freed 0 spare client objects
[ N 2022-12-15 14:08:49.7193 18812/T9 Ser/Server.h:558 ]: [ServerThr.1] Shutdown finished
[ N 2022-12-15 14:08:49.7193 18812/To Ser/Server.h:901 ]: [ApiServer] Freed 0 spare client objects
[ N 2022-12-15 14:08:49.7194 18812/To Ser/Server.h:558 ]: [ApiServer] Shutdown finished
[ N 2022-12-15 14:08:50.6730 18812/T1 age/Cor/CoreMain.cpp:1325 ]: Passenger core shutdown finished
[ N 2022-12-15 14:10:23.7548 19020/T1 age/Wat/WatchdogMain.cpp:1377 ]: Starting Passenger watchdog...
[ N 2022-12-15 14:10:23.7857 19022/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2022-12-15 14:10:23.7863 19022/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2022-12-15 14:10:23.8313 19022/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 19022
App 19044 output: Error: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
App 19044 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require'
App 19044 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
App 19044 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `require'
App 19044 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
App 19044 output:     /Users/seamusconnolly/Desktop/telegram-binance-bot/index.rb:2:in `require'
App 19044 output:     /Users/seamusconnolly/Desktop/telegram-binance-bot/index.rb:2:in `<top (required)>'
App 19044 output:     config.ru:1:in `require'
App 19044 output:     config.ru:1:in `block in <main>'
App 19044 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-3.0.2/lib/rack/builder.rb:118:in `instance_eval'
App 19044 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-3.0.2/lib/rack/builder.rb:118:in `initialize'
App 19044 output:     config.ru:1:in `new'
App 19044 output:     config.ru:1:in `<main>'
App 19044 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 19044 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 19044 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 19044 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
App 19044 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 19044 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 19044 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ N 2022-12-15 14:10:26.9543 19022/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
[ E 2022-12-15 14:10:27.0650 19022/Tr age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /Users/seamusconnolly/Desktop/telegram-binance-bot: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
  Error ID: 5f38c626
  Error details saved to: /var/folders/p_/06q3c1qn0dsbgl8rc6g82gy00000gn/T//passenger-error-Xck9S9.html

[ E 2022-12-15 14:10:27.0745 19022/T8 age/Cor/Con/CheckoutSession.cpp:283 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 5f38c626. Please see earlier logs for details about the error.
App 19104 output: Error: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
App 19104 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require'
App 19104 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
App 19104 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `require'
App 19104 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
App 19104 output:     /Users/seamusconnolly/Desktop/telegram-binance-bot/index.rb:2:in `require'
App 19104 output:     /Users/seamusconnolly/Desktop/telegram-binance-bot/index.rb:2:in `<top (required)>'
App 19104 output:     config.ru:1:in `require'
App 19104 output:     config.ru:1:in `block in <main>'
App 19104 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-3.0.2/lib/rack/builder.rb:118:in `instance_eval'
App 19104 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-3.0.2/lib/rack/builder.rb:118:in `initialize'
App 19104 output:     config.ru:1:in `new'
App 19104 output:     config.ru:1:in `<main>'
App 19104 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 19104 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 19104 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 19104 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
App 19104 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 19104 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 19104 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2022-12-15 14:10:54.5267 19022/Tw age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /Users/seamusconnolly/Desktop/telegram-binance-bot: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
  Error ID: f7705a23
  Error details saved to: /var/folders/p_/06q3c1qn0dsbgl8rc6g82gy00000gn/T//passenger-error-bp5xlZ.html

[ E 2022-12-15 14:10:54.5361 19022/Ta age/Cor/Con/CheckoutSession.cpp:283 ]: [Client 2-1] Cannot checkout session because a spawning error occurred. The identifier of the error is f7705a23. Please see earlier logs for details about the error.
App 19135 output: Error: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
App 19135 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require'
App 19135 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
App 19135 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `require'
App 19135 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
App 19135 output:     /Users/seamusconnolly/Desktop/telegram-binance-bot/index.rb:2:in `require'
App 19135 output:     /Users/seamusconnolly/Desktop/telegram-binance-bot/index.rb:2:in `<top (required)>'
App 19135 output:     config.ru:1:in `require'
App 19135 output:     config.ru:1:in `block in <main>'
App 19135 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-3.0.2/lib/rack/builder.rb:118:in `instance_eval'
App 19135 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-3.0.2/lib/rack/builder.rb:118:in `initialize'
App 19135 output:     config.ru:1:in `new'
App 19135 output:     config.ru:1:in `<main>'
App 19135 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 19135 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 19135 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 19135 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
App 19135 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 19135 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 19135 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2022-12-15 14:10:55.9500 19022/T11 age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /Users/seamusconnolly/Desktop/telegram-binance-bot: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
  Error ID: db320130
  Error details saved to: /var/folders/p_/06q3c1qn0dsbgl8rc6g82gy00000gn/T//passenger-error-HA0u5S.html

[ E 2022-12-15 14:10:55.9586 19022/Tc age/Cor/Con/CheckoutSession.cpp:283 ]: [Client 3-1] Cannot checkout session because a spawning error occurred. The identifier of the error is db320130. Please see earlier logs for details about the error.

[ N 2022-12-15 14:11:26.9067 19022/T8 age/Cor/CoreMain.cpp:671 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ N 2022-12-15 14:11:26.9068 19022/T1 age/Cor/CoreMain.cpp:1246 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ N 2022-12-15 14:11:26.9070 19022/Tc Ser/Server.h:901 ]: [ServerThr.3] Freed 0 spare client objects
[ N 2022-12-15 14:11:26.9070 19022/Te Ser/Server.h:901 ]: [ServerThr.4] Freed 0 spare client objects
[ N 2022-12-15 14:11:26.9071 19022/Ti Ser/Server.h:901 ]: [ServerThr.6] Freed 0 spare client objects
[ N 2022-12-15 14:11:26.9071 19022/Tm Ser/Server.h:901 ]: [ServerThr.8] Freed 0 spare client objects
[ N 2022-12-15 14:11:26.9071 19022/Ti Ser/Server.h:558 ]: [ServerThr.6] Shutdown finished
[ N 2022-12-15 14:11:26.9073 19022/Tm Ser/Server.h:558 ]: [ServerThr.8] Shutdown finished
[ N 2022-12-15 14:11:26.9070 19022/Ta Ser/Server.h:901 ]: [ServerThr.2] Freed 0 spare client objects
[ N 2022-12-15 14:11:26.9070 19022/Tc Ser/Server.h:558 ]: [ServerThr.3] Shutdown finished
[ N 2022-12-15 14:11:26.9070 19022/Tg Ser/Server.h:901 ]: [ServerThr.5] Freed 0 spare client objects
[ N 2022-12-15 14:11:26.9071 19022/Tk Ser/Server.h:901 ]: [ServerThr.7] Freed 0 spare client objects
[ N 2022-12-15 14:11:26.9071 19022/Te Ser/Server.h:558 ]: [ServerThr.4] Shutdown finished
[ N 2022-12-15 14:11:26.9074 19022/Tk Ser/Server.h:558 ]: [ServerThr.7] Shutdown finished
[ N 2022-12-15 14:11:26.9074 19022/Ta Ser/Server.h:558 ]: [ServerThr.2] Shutdown finished
[ N 2022-12-15 14:11:26.9074 19022/Tg Ser/Server.h:558 ]: [ServerThr.5] Shutdown finished
[ N 2022-12-15 14:11:26.9074 19022/To Ser/Server.h:901 ]: [ApiServer] Freed 0 spare client objects
[ N 2022-12-15 14:11:26.9070 19022/T8 Ser/Server.h:901 ]: [ServerThr.1] Freed 0 spare client objects
[ N 2022-12-15 14:11:26.9075 19022/To Ser/Server.h:558 ]: [ApiServer] Shutdown finished
[ N 2022-12-15 14:11:26.9076 19022/T8 Ser/Server.h:558 ]: [ServerThr.1] Shutdown finished
[ N 2022-12-15 14:11:27.8449 19022/T1 age/Cor/CoreMain.cpp:1325 ]: Passenger core shutdown finished
[ N 2022-12-15 14:11:30.8384 19255/T1 age/Wat/WatchdogMain.cpp:1377 ]: Starting Passenger watchdog...
[ N 2022-12-15 14:11:30.8661 19257/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2022-12-15 14:11:30.8664 19257/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2022-12-15 14:11:30.8891 19257/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 19257
App 19282 output: Error: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
App 19282 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require'
App 19282 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
App 19282 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `require'
App 19282 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
App 19282 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `require'
App 19282 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `<top (required)>'
App 19282 output:     /Users/seamusconnolly/Desktop/telegram-binance-bot/index.rb:2:in `require'
App 19282 output:     /Users/seamusconnolly/Desktop/telegram-binance-bot/index.rb:2:in `<top (required)>'
App 19282 output:     config.ru:1:in `require'
App 19282 output:     config.ru:1:in `block in <main>'
App 19282 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-3.0.2/lib/rack/builder.rb:118:in `instance_eval'
App 19282 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-3.0.2/lib/rack/builder.rb:118:in `initialize'
App 19282 output:     config.ru:1:in `new'
App 19282 output:     config.ru:1:in `<main>'
App 19282 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 19282 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 19282 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 19282 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
App 19282 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 19282 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 19282 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2022-12-15 14:11:33.8478 19257/Tr age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /Users/seamusconnolly/Desktop/telegram-binance-bot: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
  Error ID: c48f815c
  Error details saved to: /var/folders/p_/06q3c1qn0dsbgl8rc6g82gy00000gn/T//passenger-error-zPcqvr.html

[ E 2022-12-15 14:11:33.8596 19257/T8 age/Cor/Con/CheckoutSession.cpp:283 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is c48f815c. Please see earlier logs for details about the error.
[ N 2022-12-15 14:11:33.9271 19257/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
[ E 2022-12-15 14:11:33.9407 19257/T5 Sec/Crypto.cpp:990 ]: Removing Passenger private key from keychain failed: Write permissions error.. Please remove the private key from the certificate labeled Phusion Passenger Open Source in your keychain.
App 19335 output: Error: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
App 19335 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require'
App 19335 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
App 19335 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `require'
App 19335 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
App 19335 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `require'
App 19335 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `<top (required)>'
App 19335 output:     /Users/seamusconnolly/Desktop/telegram-binance-bot/index.rb:2:in `require'
App 19335 output:     /Users/seamusconnolly/Desktop/telegram-binance-bot/index.rb:2:in `<top (required)>'
App 19335 output:     config.ru:1:in `require'
App 19335 output:     config.ru:1:in `block in <main>'
App 19335 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-3.0.2/lib/rack/builder.rb:118:in `instance_eval'
App 19335 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-3.0.2/lib/rack/builder.rb:118:in `initialize'
App 19335 output:     config.ru:1:in `new'
App 19335 output:     config.ru:1:in `<main>'
App 19335 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 19335 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 19335 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 19335 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
App 19335 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 19335 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 19335 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2022-12-15 14:12:05.1971 19257/Tw age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /Users/seamusconnolly/Desktop/telegram-binance-bot: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
  Error ID: 2f8af7ce
  Error details saved to: /var/folders/p_/06q3c1qn0dsbgl8rc6g82gy00000gn/T//passenger-error-NS1j7h.html

[ E 2022-12-15 14:12:05.2058 19257/Tb age/Cor/Con/CheckoutSession.cpp:283 ]: [Client 2-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 2f8af7ce. Please see earlier logs for details about the error.
App 19366 output: Error: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
App 19366 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require'
App 19366 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
App 19366 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `require'
App 19366 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
App 19366 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `require'
App 19366 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/sinatra-1.0/lib/sinatra.rb:4:in `<top (required)>'
App 19366 output:     /Users/seamusconnolly/Desktop/telegram-binance-bot/index.rb:2:in `require'
App 19366 output:     /Users/seamusconnolly/Desktop/telegram-binance-bot/index.rb:2:in `<top (required)>'
App 19366 output:     config.ru:1:in `require'
App 19366 output:     config.ru:1:in `block in <main>'
App 19366 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-3.0.2/lib/rack/builder.rb:118:in `instance_eval'
App 19366 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-3.0.2/lib/rack/builder.rb:118:in `initialize'
App 19366 output:     config.ru:1:in `new'
App 19366 output:     config.ru:1:in `<main>'
App 19366 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 19366 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 19366 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 19366 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
App 19366 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 19366 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 19366 output:     /Users/seamusconnolly/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/passenger-6.0.15/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2022-12-15 14:12:06.3442 19257/T11 age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /Users/seamusconnolly/Desktop/telegram-binance-bot: The application encountered the following error: cannot load such file -- rack/showexceptions (LoadError)
  Error ID: aed3dc0d
  Error details saved to: /var/folders/p_/06q3c1qn0dsbgl8rc6g82gy00000gn/T//passenger-error-wGiWxh.html

[ E 2022-12-15 14:12:06.3530 19257/Tc age/Cor/Con/CheckoutSession.cpp:283 ]: [Client 3-1] Cannot checkout session because a spawning error occurred. The identifier of the error is aed3dc0d. Please see earlier logs for details about the error.

[ N 2022-12-15 14:12:36.4575 19257/T8 age/Cor/CoreMain.cpp:671 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ N 2022-12-15 14:12:36.4576 19257/T1 age/Cor/CoreMain.cpp:1246 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ N 2022-12-15 14:12:36.4577 19257/T8 Ser/Server.h:901 ]: [ServerThr.1] Freed 0 spare client objects
[ N 2022-12-15 14:12:36.4577 19257/T8 Ser/Server.h:558 ]: [ServerThr.1] Shutdown finished
[ N 2022-12-15 14:12:36.4577 19257/Te Ser/Server.h:901 ]: [ServerThr.4] Freed 0 spare client objects
[ N 2022-12-15 14:12:36.4577 19257/Te Ser/Server.h:558 ]: [ServerThr.4] Shutdown finished
[ N 2022-12-15 14:12:36.4577 19257/Ti Ser/Server.h:901 ]: [ServerThr.6] Freed 0 spare client objects
[ N 2022-12-15 14:12:36.4578 19257/Tm Ser/Server.h:901 ]: [ServerThr.8] Freed 0 spare client objects
[ N 2022-12-15 14:12:36.4577 19257/Tk Ser/Server.h:901 ]: [ServerThr.7] Freed 0 spare client objects
[ N 2022-12-15 14:12:36.4577 19257/Tg Ser/Server.h:901 ]: [ServerThr.5] Freed 0 spare client objects
[ N 2022-12-15 14:12:36.4578 19257/Tm Ser/Server.h:558 ]: [ServerThr.8] Shutdown finished
[ N 2022-12-15 14:12:36.4578 19257/Tk Ser/Server.h:558 ]: [ServerThr.7] Shutdown finished
[ N 2022-12-15 14:12:36.4578 19257/Ti Ser/Server.h:558 ]: [ServerThr.6] Shutdown finished
[ N 2022-12-15 14:12:36.4578 19257/Tg Ser/Server.h:558 ]: [ServerThr.5] Shutdown finished
[ N 2022-12-15 14:12:36.4577 19257/Tb Ser/Server.h:901 ]: [ServerThr.2] Freed 0 spare client objects
[ N 2022-12-15 14:12:36.4577 19257/Tc Ser/Server.h:901 ]: [ServerThr.3] Freed 0 spare client objects
[ N 2022-12-15 14:12:36.4579 19257/Tp Ser/Server.h:901 ]: [ApiServer] Freed 0 spare client objects
[ N 2022-12-15 14:12:36.4579 19257/Tc Ser/Server.h:558 ]: [ServerThr.3] Shutdown finished
[ N 2022-12-15 14:12:36.4579 19257/Tp Ser/Server.h:558 ]: [ApiServer] Shutdown finished
[ N 2022-12-15 14:12:36.4579 19257/Tb Ser/Server.h:558 ]: [ServerThr.2] Shutdown finished
[ N 2022-12-15 14:12:37.3115 19257/T1 age/Cor/CoreMain.cpp:1325 ]: Passenger core shutdown finished
